interface Addin {
	group: AddinGroup;
	uniqueName: string;
	displayName: string;
	fullPath: string;
	macroses(): string[];
	invokeMacros(macros: string);
	menu(): string[];
	invokeMenu(idx: number): void;
	object(): Object;
}
interface AddinGroup {
	name: string;
	parent: AddinGroup;
	child: AddinGroup;
	next: AddinGroup;
	childs: AddinGroup[];
	addins: Addin[];
	addGroup(nameOfChild: string): AddinGroup;
	addAddin(addin: Addin): void;
	addinsCount: number;
	addin(idx: number): Addin;
}
interface AddinMgr {
	root: AddinGroup;
	libs: AddinGroup;
	users: AddinGroup;
	sys: AddinGroup;
	lastAddinError: string;
	count: number;
	byUniqueName(name: string): Addin;
	byFullPath(fullPath: string): Addin;
	byIdx(idx: number): Addin;
	loadAddin(uri: string, group: AddinGroup): Addin;
	unloadAddin(addin: Addin): boolean;
	getLoaderCommands(): string[];
	selectAndLoad(loaderCommand: string, group: AddinGroup): Addin;
	isAddinUnloadable(addin: Addin): boolean;
	enterInAddinRun(addin: Addin): void;
	leaveAddinRun(addin: Addin): void;
}
interface ProfileStore {
	name: string;
	createValue(path2value: string, defaultValue, storeType: number): void;
	getValue(path2value: string);
	setValue(path2value: string, value): void;
	valuesCount: number;
	valueName(idx: number): string;
	getValueAt(idx: number);
	setValueAt(idx: number, value): void;
	deleteValue(name: string): void;
	deleteValueAt(idx: number): void;
	createFolder(folderName: string, storeType: number): void;
	foldersCount: number;
	getFolder(path2folder: string): ProfileStore;
	getFolderAt(idx: number): ProfileStore;
	deleteFolder(name: string): void;
	deleteFolderAt(idx: number): void;
}
interface OptionsEntry {
	next: OptionsEntry;
	name: string;
	profile: string;
	doApply(newVal): boolean;
}
interface Selection {
	beginRow: number;
	beginCol: number;
	endRow: number;
	endCol: number;
}
interface IV8MDProperty {
	id: string;
	name(langAliase: number): string;
	description: string;
	category: string;
}
interface IV8MDClass {
	id: string;
	name(langAliase: number, pluralForm?: boolean): string;
	presentation(pluralForm?: boolean): string;
	propertiesCount: number;
	propertyAt(idx: number): IV8MDProperty;
	childsClassesCount: number;
	childClassAt(idx: number): IV8MDClass;
}
interface MemoryBuffer {
	bytes: number;
	length: number;
	byte(pos: number): number;
}
interface IV8DataFile {
	file;
	read(length: number): MemoryBuffer;
	write(bytes: MemoryBuffer): void;
	seek(pos: number, fsMode: number): number;
	getString(mode: number, length?: number): string;
	putString(mode: number, str: string, length?: number): void;
	flush(): void;
	setEOF(): void;
	url: string;
	close(): void;
}
interface IV8ExtProp {
	object: Object;
	url: string;
	idData: string;
	idEditor: string;
	title: string;
	isReadOnly: boolean;
	saveToFile(file?: IV8DataFile): IV8DataFile;
	loadFromFile(file: IV8DataFile): boolean;
	getForm();
}
interface IObjectProperties {
	count: number;
	propName(idx: number): string;
	getValue(idx);
	setValue(idx, val): void;
	activateProperty(idx): void;
}
interface IV8MDObject {
	isSame(other: IV8MDObject): boolean;
	id: string;
	mdclass: IV8MDClass;
	parent: IV8MDObject;
	property(propID);
	setProperty(propID, value): boolean;
	childObjectsCount(childClassID): number;
	childObject(childClassID, idx): IV8MDObject;
	container: IV8MDContainer;
	activateInTree(): void;
	editProperty(propID): void;
	openEditor(): void;
	name: string;
	types(): string[];
	synonym(langCode: string): string;
	comment: string;
	isPropModule(propIdx): boolean;
	getModuleText(propIdx): string;
	setModuleText(propIdx, text: string): void;
	openModule(propIdx): ITextWindow;
	extPropUUID(propIdx): string;
	getExtProp(propIdx): IV8ExtProp;
	saveToFile(fileIn?: IV8DataFile): IV8DataFile;
	loadFromFile(file: IV8DataFile): boolean;
	picture;
	props: IObjectProperties;
}
interface V8TypeInfo {
	name: string;
	clsid: string;
	order1: number;
	order2: number;
	picture;
}
interface IV8MDContainer {
	closed: boolean;
	rootObject: IV8MDObject;
	typeList(typeCategories: string, lang: number): V8TypeInfo[];
	masterContainer: IV8MDContainer;
	isModified: boolean;
	treeVisible: boolean;
	findByUUID(uuid: string): IV8MDObject;
	findByTypeUUID(uuid: string): IV8MDObject;
	identifier: string;
	saveToFile(path: string): boolean;
}
interface ITextWindow {
	multyEdit: boolean;
	isAlive: boolean;
	text: string;
	getSelection(): Selection;
	setSelection(beginRow: number, beginCol: number, endRow: number, endCol: number): void;
	selectedText: string;
	getCaretPos(): Selection;
	setCaretPos(row: number, col: number): void;
	linesCount: number;
	line(lineNumber: number): string;
	readOnly: boolean;
	hwnd: number;
	textMgr: number;
	extName(): string;
	textDocument;
	mdCont: IV8MDContainer;
	mdObj: IV8MDObject;
	mdProp: IV8MDProperty;
	extObject;
}
interface ILexem {
	type: number;
	start: number;
	length: number;
	line: number;
	text: string;
}
interface IV8Lexer {
	text: string;
	reStream: string;
	lexemCount: number;
	lexem(idx: number): ILexem;
	namesCount: number;
	name(idx: number): string;
	idxOfName(name: string): number;
	posToLexem(posInReStream: number): number;
	strNameIdx(name: string): string;
}
interface Snegopat {
	optionEntries: OptionsEntry;
	activeTextWindow(): ITextWindow;
	parseTemplateString(text: string, name?: string): string;
	showMethodsList(): boolean;
	showSmartBox(): boolean;
	parseSources(strSource: string, startLine?: number): IV8Lexer;
	updateAllEditorsSettings(): void;
	getStockTextIndent(): string;
}
interface IHotKey {
	addin: string;
	macros: string;
	presentation: string;
	key: number;
	setCommand(newAddin: string, Macros: string): void;
}
interface IHotKeys {
	item(Idx: number): IHotKey;
	count: number;
	remove(Idx: number): void;
	add(Key: number, addinName: string, Macros: string): IHotKey;
	clearAll(): void;
	addTemp(Key: number, addinName: string, Macros: string): number;
	removeTemp(hkID: number): void;
	addTempFunction(Key: number, disp: Object, name?: string): number;
	hotKeyToString(code: number): string;
}
interface HandlerNode {
	handler: Object;
	nameOfHandler: string;
	removed: boolean;
}
interface IEventConnector {
	connect(pSource: Object, eventName: string, handler: Object, handlerName?: string): HandlerNode;
	disconnect(pSource: Object, eventName: string, handler: Object, handlerName?: string): void;
	disconnectNode(node: HandlerNode): void;
	fireEvent(pSource: Object, eventName: string, args: any[]): void;
	addCommandHandler(cmdGroupUUID: string, cmdNumber: number, handler: Object, handlerName: string): HandlerNode;
	delCommandHandler(cmdGroupUUID: string, cmdNumber: number, handler: Object, handlerName: string): void;
	removeMyListeners(pSource: Object): void;
}
interface IV8ViewPosition {
	vp;
}
interface ICmdUpdateResult {
	enabled: boolean;
	checked: boolean;
	text: string;
	description: string;
	tooltip: string;
	subCommands: number;
}
interface IViewDocument {
}
interface IExtControl {
}
interface IV8Control {
	value;
	id: number;
	name: string;
	hwnd: number;
	extInterface: IExtControl;
	props: IObjectProperties;
}
interface IV8Form {
	detach(): void;
	controlsCount: number;
	getControl(IdxOrCode): IV8Control;
	trapDialogEvents: boolean;
	put_trapDialogEvents(newVal: boolean): void;
	sendEvent(ctrlID: number, eventID: number, ... args): void;
	getCmdState(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?): ICmdUpdateResult;
	sendCommand(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): boolean;
	getCtrlCmdState(ctrlID: number, cmdGroupUUID: string, cmdNumber: number, subCommandIdx?): ICmdUpdateResult;
	sendCtrlCommand(ctrlID: number, cmdGroupUUID: string, cmdNumber: number, subCommandIdx: number): boolean;
	activeControl: IV8Control;
}
interface IV8View {
	isAlive(): boolean;
	id: string;
	title: string;
	hwnd: number;
	position(): IV8ViewPosition;
	parent: IV8View;
	enumChilds(): IV8View[];
	merge(other: IV8View, place: number): void;
	isContainer: number;
	wndClass: string;
	visible: boolean;
	activeChild: IV8View;
	activate(): void;
	close(forceClose?: boolean): void;
	getCmdState(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): ICmdUpdateResult;
	sendCommand(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): boolean;
	getDocument(): IViewDocument;
	getObject();
	getInternalForm(): IV8Form;
	icon;
	mdObj: IV8MDObject;
	mdProp: IV8MDProperty;
}
interface IV8Windows {
	mainView: IV8View;
	mdiView: IV8View;
	modalMode: number;
	caption: string;
	mainTitle: string;
	additionalTitle: string;
	propsVisible: boolean;
	getActiveView(): IV8View;
	getFocusedView(): IV8View;
	getInputFieldText(ctrl): string;
}
interface IV8MetaData {
	ib: IV8MDContainer;
	current: IV8MDContainer;
	mdClass(uuid: string): IV8MDClass;
	mdProp(uuid: string): IV8MDProperty;
	openedCount: number;
	getContainer(idx: number): IV8MDContainer;
}
interface IV8StorageFile {
	stg;
	files(): string[];
	open(name: string, mode: number): IV8DataFile;
	rename(oldName: string, newName: string): void;
	remove(name: string): void;
}
interface V8Files {
	open(path: string, mode: number): IV8DataFile;
	createMemoryFile(): IV8DataFile;
	createTempFile(memLimit?: number): IV8DataFile;
	attachStorage(file: IV8DataFile, createNew?: boolean): IV8StorageFile;
	newMemoryBuffer(size: number): MemoryBuffer;
}
interface Develop {
	cmdTrace: boolean;
	dumpV8typesToDts(): void;
	dumpSnegApiToDts(): void;
}
interface Pathes {
	main: string;
	core: string;
	addins: string;
	tools: string;
	data: string;
	help: string;
	custom: string;
	repo: string;
	tmp: string;
}
interface EnvironmentData {
	sVersion: string;
	v8Version: string;
	v8ver: number;
	snMainFolder: string;
	ownerName: string;
	BuildDateTime: string;
	pathes: Pathes;
}
interface CommandDescription {
	group: string;
	num: number;
	text: string;
	accel: string;
	picture;
	description: string;
	tooltip: string;
	presentation: string;
}
interface CommandService {
	getCommandDescription(groupUuid: string, number: number): CommandDescription;
}
interface WinApi {
	getFocus(): number;
	sendMessage(hWnd: number, message: number, w: number, l: number): number;
}
interface V8Value {
	value;
	typeName(language?: number): string;
	presentation(): string;
	isObject: boolean;
	contextInfo(): string;
	toStringInternal(): string;
	typeUUID(): string;
}
interface ComEditorInfo {
	name: string;
	extention: string;
}
interface EditorsManager {
	count(): number;
	editor(idx: number): ComEditorInfo;
	setActiveEditor(extName: string, editorName: string): boolean;
	setup(editorName: string): void;
}
interface SqliteQuery {
	stmt: number;
	bind(idx, val): SqliteQuery;
	exec(isAnswerID?: boolean);
	queryRow();
	queryValue();
	close(): void;
}
interface SqliteBase {
	db: number;
	exec(strQuery: string, answerIsID?: boolean, resArray?);
	lastError: string;
	close(): void;
	prepare(strQuery: string): SqliteQuery;
	changes(): number;
	totalChanges(): number;
	lastInsertedID(): number;
}
interface _IfaceDesigner {
	addins: AddinMgr;
	profileRoot: ProfileStore;
	snegopat: Snegopat;
	hotkeys: IHotKeys;
	events: IEventConnector;
	windows: IV8Windows;
	metadata: IV8MetaData;
	v8files: V8Files;
	develop: Develop;
	env: EnvironmentData;
	cmdService: CommandService;
	winApi: WinApi;
	v8New(name: string, ... params);
	Message(text: string, markerOrPict?, clickHandler?: Object, handlerArg?): void;
	MessageBox(text: string, style?: number, caption?: string, timeout?: number): number;
	globalContext(uuidStr: string);
	designInternalForm(path?: string): void;
	designScriptForm(path?: string): void;
	loadScriptForm(path: string, eventHandler: Object, eventPrefix?: string);
	loadScriptFormEpf(path: string, formName: string, eventHandler: Object, eventPrefix?: string);
	toV8Value(varValue): V8Value;
	getCmdState(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): ICmdUpdateResult;
	sendCommand(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): boolean;
	createTimer(msec: number, pDisp: Object, member?: string): number;
	killTimer(timerID: number): void;
	saveProfile(): void;
	snPrint(msg: string): void;
	snLog(msg: string): void;
	editorsManager: EditorsManager;
	loadResourceString(moduleName: string, stringID: string): string;
	builtin_require(addinFile: string);
	sqliteOpen(baseName?: string, flags?: number): SqliteBase;
}
interface _IfaceSelfScript {
	fullPath: string;
	uniqueName: string;
	displayName: string;
	self: Object;
	addNamedItem(name: string, unk: Object, global?: boolean): void;
}
declare function ScriptEngineMajorVersion():number;
declare function ScriptEngineMinorVersion():number;
declare var asCALL_CDECL: number;
declare var asCALL_STDCALL: number;
declare var asCALL_THISCALL: number;
declare var cmBegin: number;
declare var cmBeginWithOtherLangs: number;
declare var cmContain: number;
declare var symbSpace: number;
declare var symbAlpha: number;
declare var symbolClassTable: number;
declare var navFirst: number;
declare var navLast: number;
declare var navNext: number;
declare var navPrev: number;
declare var navNextPage: number;
declare var navPrevPage: number;
declare var endOfText: number;
declare var lexUnknown: number;
declare var lexRemark: number;
declare var lexQuote: number;
declare var lexQuoteOpen: number;
declare var lexDate: number;
declare var lexDateOpen: number;
declare var lexNumber: number;
declare var lexPreproc: number;
declare var lexDirective: number;
declare var lexLabel: number;
declare var lexLPar: number;
declare var lexRPar: number;
declare var lexLBrt: number;
declare var lexRBrt: number;
declare var lexEqual: number;
declare var lexComma: number;
declare var lexSemicolon: number;
declare var lexPlus: number;
declare var lexMinus: number;
declare var lexMult: number;
declare var lexDivide: number;
declare var lexMod: number;
declare var lexQuestion: number;
declare var lexPeriod: number;
declare var lexLess: number;
declare var lexLessEq: number;
declare var lexGrat: number;
declare var lexGratEq: number;
declare var lexNotEq: number;
declare var lexName: number;
declare var kwIf: number;
declare var kwThen: number;
declare var kwElsIf: number;
declare var kwEndIf: number;
declare var kwElse: number;
declare var kwFor: number;
declare var kwEach: number;
declare var kwIn: number;
declare var kwTo: number;
declare var kwWhile: number;
declare var kwDo: number;
declare var kwEndDo: number;
declare var kwProcedure: number;
declare var kwFunction: number;
declare var kwEndProcedure: number;
declare var kwEndFunction: number;
declare var kwVar: number;
declare var kwGoto: number;
declare var kwReturn: number;
declare var kwContinue: number;
declare var kwBreak: number;
declare var kwAnd: number;
declare var kwOr: number;
declare var kwNot: number;
declare var kwTry: number;
declare var kwExcept: number;
declare var kwRaise: number;
declare var kwEndTry: number;
declare var kwNew: number;
declare var kwExecute: number;
declare var kwTrue: number;
declare var kwFalse: number;
declare var kwAddHandler: number;
declare var kwRemoveHandler: number;
declare var kwExport: number;
declare var kwNull: number;
declare var kwUndefined: number;
declare var kwVal: number;
declare var onlyMeths: number;
declare var onlyMethsAndStatements: number;
declare var onlyVarsAndMethods: number;
declare var currentLexem: number;
declare var kwCount: number;
declare var hkCtrl: number;
declare var hkAlt: number;
declare var hkShift: number;
declare var VT_EMPTY: number;
declare var VT_NULL: number;
declare var VT_I2: number;
declare var VT_I4: number;
declare var VT_R4: number;
declare var VT_R8: number;
declare var VT_CY: number;
declare var VT_DATE: number;
declare var VT_BSTR: number;
declare var VT_DISPATCH: number;
declare var VT_ERROR: number;
declare var VT_BOOL: number;
declare var VT_VARIANT: number;
declare var VT_UNKNOWN: number;
declare var VT_DECIMAL: number;
declare var VT_I1: number;
declare var VT_UI1: number;
declare var VT_UI2: number;
declare var VT_UI4: number;
declare var VT_I8: number;
declare var VT_UI8: number;
declare var VT_INT: number;
declare var VT_UINT: number;
declare var VT_VOID: number;
declare var VT_HRESULT: number;
declare var VT_PTR: number;
declare var VT_SAFEARRAY: number;
declare var VT_CARRAY: number;
declare var VT_USERDEFINED: number;
declare var VT_LPSTR: number;
declare var VT_LPWSTR: number;
declare var VT_RECORD: number;
declare var VT_INT_PTR: number;
declare var VT_UINT_PTR: number;
declare var VT_FILETIME: number;
declare var VT_BLOB: number;
declare var VT_STREAM: number;
declare var VT_STORAGE: number;
declare var VT_STREAMED_OBJECT: number;
declare var VT_STORED_OBJECT: number;
declare var VT_BLOB_OBJECT: number;
declare var VT_CF: number;
declare var VT_CLSID: number;
declare var VT_VERSIONED_STREAM: number;
declare var VT_BSTR_BLOB: number;
declare var VT_VECTOR: number;
declare var VT_ARRAY: number;
declare var VT_BYREF: number;
declare var VT_RESERVED: number;
declare var VT_ILLEGAL: number;
declare var VT_ILLEGALMASKED: number;
declare var VT_TYPEMASK: number;
declare var VARIANT_TRUE: number;
declare var VARIANT_FALSE: number;
declare var trapNotActive: number;
declare var trapDisabled: number;
declare var trapEnabled: number;
declare var IBkEndUI_doModal1: number;
declare var IBkEndUI_messageBox: number;
declare var IBkEndUI_doModal2: number;
declare var IBkEndUI_doMsgLine: number;
declare var IBkEndUI_GetFileName: number;
declare var ICommandTarget_onExecute: number;
declare var ICommandReceiver_transmitCommand: number;
declare var IExternalCalculatorOwner_setExternalCalculator: number;
declare var IDocument_createView: number;
declare var IFileSystem_openURL: number;
declare var IMDEditService_openConfig: number;
declare var IMDClass_childClassIDAt: number;
declare var IProfileService_open: number;
declare var ITextEditor_setSelectionNull: number;
declare var ITextEditor_setCaretPosition: number;
declare var ITextEditor_scrollToCaretPos: number;
declare var ITextEditor_setSelection: number;
declare var ITextManager_Operations_setExtenderCLSID: number;
declare var ISourceLexer_splitToLexems: number;
declare var ITEIntelliSence_getContextListPos: number;
declare var ITextExtBackColors_hasCustomBackground: number;
declare var ITextExtBackColors_getColorInfo: number;
declare var ITextExtColors_getColors: number;
declare var IAssistList_getDataSource: number;
declare var IWindowView_createWindow: number;
declare var IFramedView_localFrame: number;
declare var IFramedView_onActivate: number;
declare var IFramedView_onInitialUpdate: number;
declare var IFramedView_onFinalOpen: number;
declare var IFramedView_mdiType: number;
declare var IDocumentView_localFrame: number;
declare var IDocumentView_onActivate: number;
declare var IDocumentView_onInitialUpdate: number;
declare var IDocumentView_onFinalOpen: number;
declare var IDocumentView_mdiType: number;
declare var ITopLevelFrame_setTitle: number;
declare var ITopLevelFrame_setAdditionalTitle: number;
declare var mNone: number;
declare var mTriangle: number;
declare var mExc1: number;
declare var mExc2: number;
declare var mExc3: number;
declare var mInfo: number;
declare var mbOK: number;
declare var mbOkCancel: number;
declare var mbAbortRetryIgnore: number;
declare var mbYesNoCancel: number;
declare var mbYesNo: number;
declare var mbRetryCancel: number;
declare var mbIconError: number;
declare var mbIconQuestion: number;
declare var mbIconWarning: number;
declare var mbIconInformation: number;
declare var mbDefButton1: number;
declare var mbDefButton2: number;
declare var mbDefButton3: number;
declare var mbaOK: number;
declare var mbaCancel: number;
declare var mbaAbort: number;
declare var mbaRetry: number;
declare var mbaIgnore: number;
declare var mbaYes: number;
declare var mbaNo: number;
declare var sfOpen: number;
declare var sfSave: number;
declare var sfFolder: number;
declare var sfMultiSelect: number;
declare var sfPromptCreate: number;
declare var sfFileMustExist: number;
declare var sfDisableChangeDir: number;
declare var sfPromptOverwrite: number;
declare var sfUsePreview: number;
declare var TKIND_ENUM: number;
declare var TKIND_RECORD: number;
declare var TKIND_MODULE: number;
declare var TKIND_INTERFACE: number;
declare var TKIND_DISPATCH: number;
declare var FUNC_VIRTUAL: number;
declare var FUNC_PUREVIRTUAL: number;
declare var FUNC_NONVIRTUAL: number;
declare var FUNC_STATIC: number;
declare var FUNC_DISPATCH: number;
declare var INVOKE_FUNC: number;
declare var INVOKE_PROPERTYGET: number;
declare var INVOKE_PROPERTYPUT: number;
declare var cmdFindInTree: number;
declare var cmdFrameShowAssist: number;
declare var cmdFrameShowParams: number;
declare var cmdQueryWizard: number;
declare var stTable: number;
declare var stTree: number;
declare var ltParent: number;
declare var ltFirstChild: number;
declare var ltLastChild: number;
declare var ltPrev: number;
declare var ltNext: number;
declare var ltSelf: number;
declare var eNone: number;
declare var eUp: number;
declare var eCenter: number;
declare var eDown: number;
declare var eChangeBookmark: number;
declare var eShowTreeLevel: number;
declare var cfText: number;
declare var cfImage: number;
declare var cfAddImage: number;
declare var cfCheck: number;
declare var cfAddCheck: number;
declare var cfBkgColor: number;
declare var cfTextColor: number;
declare var cfReadOnly: number;
declare var cfHorAlign: number;
declare var cfTextFont: number;
declare var cfTooltipText: number;
declare var cfVisible: number;
declare var cfHeight: number;
declare var cfAutoHeight: number;
declare var cfHyperLink: number;
declare var csNotChecked: number;
declare var csChecked: number;
declare var csGrayed: number;
declare var ehaLeft: number;
declare var ehaCenter: number;
declare var ehaRight: number;
declare var ehaJustify: number;
declare var ehaAuto: number;
declare var evaTop: number;
declare var evaCenter: number;
declare var evaBottom: number;
declare var idleHandlerUnknownFuncAnswer: number;
declare var fomAppend: number;
declare var fomTruncate: number;
declare var fomIn: number;
declare var fomOut: number;
declare var fomShareRead: number;
declare var fomShareWrite: number;
declare var fsBegin: number;
declare var fsCurrent: number;
declare var fsEnd: number;
declare var scfNone: number;
declare var scfCached: number;
declare var scfTruncate: number;
declare var fkLogfont: number;
declare var fkSystem: number;
declare var fkStyle: number;
declare var fkAuto: number;
declare var MetaDataObjInEventRecipientOffset: number;
declare var emdAddChild: number;
declare var emdPropChanged: number;
declare var emdDeleteChild: number;
declare var emdChanged: number;
declare var emdSave: number;
declare var emdClose: number;
declare var emdAfterSave: number;
declare var pictOffset: number;
declare var SQLITE_OK: number;
declare var SQLITE_ERROR: number;
declare var SQLITE_INTERNAL: number;
declare var SQLITE_PERM: number;
declare var SQLITE_ABORT: number;
declare var SQLITE_BUSY: number;
declare var SQLITE_LOCKED: number;
declare var SQLITE_NOMEM: number;
declare var SQLITE_READONLY: number;
declare var SQLITE_INTERRUPT: number;
declare var SQLITE_IOERR: number;
declare var SQLITE_CORRUPT: number;
declare var SQLITE_NOTFOUND: number;
declare var SQLITE_FULL: number;
declare var SQLITE_CANTOPEN: number;
declare var SQLITE_PROTOCOL: number;
declare var SQLITE_EMPTY: number;
declare var SQLITE_SCHEMA: number;
declare var SQLITE_TOOBIG: number;
declare var SQLITE_CONSTRAINT: number;
declare var SQLITE_MISMATCH: number;
declare var SQLITE_MISUSE: number;
declare var SQLITE_NOLFS: number;
declare var SQLITE_AUTH: number;
declare var SQLITE_FORMAT: number;
declare var SQLITE_RANGE: number;
declare var SQLITE_NOTADB: number;
declare var SQLITE_NOTICE: number;
declare var SQLITE_WARNING: number;
declare var SQLITE_ROW: number;
declare var SQLITE_DONE: number;
declare var SQLITE_INTEGER: number;
declare var SQLITE_FLOAT: number;
declare var SQLITE_TEXT: number;
declare var SQLITE_BLOB: number;
declare var SQLITE_NULL: number;
declare var SQLITE_STATIC: number;
declare var SQLITE_TRANSIENT: number;
declare var SQLITE_OPEN_READONLY: number;
declare var SQLITE_OPEN_READWRITE: number;
declare var SQLITE_OPEN_CREATE: number;
declare var SQLITE_OPEN_DELETEONCLOSE: number;
declare var SQLITE_OPEN_EXCLUSIVE: number;
declare var SQLITE_OPEN_AUTOPROXY: number;
declare var SQLITE_OPEN_URI: number;
declare var SQLITE_OPEN_MEMORY: number;
declare var SQLITE_OPEN_MAIN_DB: number;
declare var SQLITE_OPEN_TEMP_DB: number;
declare var SQLITE_OPEN_TRANSIENT_DB: number;
declare var SQLITE_OPEN_MAIN_JOURNAL: number;
declare var SQLITE_OPEN_TEMP_JOURNAL: number;
declare var SQLITE_OPEN_SUBJOURNAL: number;
declare var SQLITE_OPEN_MASTER_JOURNAL: number;
declare var SQLITE_OPEN_NOMUTEX: number;
declare var SQLITE_OPEN_FULLMUTEX: number;
declare var SQLITE_OPEN_SHAREDCACHE: number;
declare var SQLITE_OPEN_PRIVATECACHE: number;
declare var SQLITE_OPEN_WAL: number;
declare var inplaceStringSize: number;
declare var ctrlDesign: number;
declare var ctrlRunning: number;
declare var symbCaret: number;
declare var cmdTxtToggleBookmark: number;
declare var cmdTxtNextBookmark: number;
declare var cmdTxtPrevBookmark: number;
declare var cmdTxtClearBookmarks: number;
declare var cmdTxtFormatBlock: number;
declare var cmdTxtMoveBlockRight: number;
declare var cmdTxtMoveBlockLeft: number;
declare var cmdTxtInsertPageBreak: number;
declare var cmdTxtParams: number;
declare var cmdTxtGotoLine: number;
declare var cmdProcessTemplate: number;
declare var ModuleTxtExtSettingsMap: number;
declare var ckRGB: number;
declare var ckIdxWin: number;
declare var ckIdxWeb: number;
declare var ckIdxStyle: number;
declare var ckAuto: number;
declare var bmNone: number;
declare var bmBegin: number;
declare var bmInner: number;
declare var bmEnd: number;
declare var groupBlockBegin: number;
declare var groupBlockEnd: number;
declare var groupBlockKind: number;
declare var vlKeyword: number;
declare var vlNumeric: number;
declare var vlString: number;
declare var vlDate: number;
declare var vlName: number;
declare var vlOperator: number;
declare var vlRemark: number;
declare var vlUnknown: number;
declare var tcfContext: number;
declare var tcfGlobal: number;
declare var tcfCmnModule: number;
declare var tcfModuleSelf: number;
declare var tcfTemplate: number;
declare var tcfKeyword: number;
declare var tkUndefined: number;
declare var tkNull: number;
declare var tkBoolean: number;
declare var tkNumeric: number;
declare var tkString: number;
declare var tkDate: number;
declare var tkObject: number;
declare var tkType: number;
declare var WM_DESTROY: number;
declare var WM_MOVE: number;
declare var WM_SIZE: number;
declare var WM_SETFOCUS: number;
declare var WM_KILLFOCUS: number;
declare var WM_PAINT: number;
declare var WM_CLOSE: number;
declare var WM_GETMINMAXINFO: number;
declare var WM_SETFONT: number;
declare var WM_NOTIFY: number;
declare var WM_NCCALCSIZE: number;
declare var WM_KEYDOWN: number;
declare var WM_KEYUP: number;
declare var WM_CHAR: number;
declare var WM_DEADCHAR: number;
declare var WM_SYSKEYDOWN: number;
declare var WM_SYSKEYUP: number;
declare var WM_SYSDEADCHAR: number;
declare var WM_UNICHAR: number;
declare var WM_INITDIALOG: number;
declare var WM_COMMAND: number;
declare var WM_LBUTTONDOWN: number;
declare var WM_LBUTTONUP: number;
declare var WM_RBUTTONDOWN: number;
declare var WM_RBUTTONUP: number;
declare var WM_SIZING: number;
declare var EN_CHANGE: number;
declare var WM_HOTKEY: number;
declare var WM_CONTEXTMENU: number;
declare var DEFAULT_GUI_FONT: number;
declare var VK_LBUTTON: number;
declare var VK_RBUTTON: number;
declare var VK_CANCEL: number;
declare var VK_MBUTTON: number;
declare var VK_XBUTTON1: number;
declare var VK_XBUTTON2: number;
declare var VK_BACK: number;
declare var VK_TAB: number;
declare var VK_CLEAR: number;
declare var VK_RETURN: number;
declare var VK_SHIFT: number;
declare var VK_CONTROL: number;
declare var VK_MENU: number;
declare var VK_PAUSE: number;
declare var VK_CAPITAL: number;
declare var VK_KANA: number;
declare var VK_HANGEUL: number;
declare var VK_HANGUL: number;
declare var VK_JUNJA: number;
declare var VK_FINAL: number;
declare var VK_HANJA: number;
declare var VK_KANJI: number;
declare var VK_ESCAPE: number;
declare var VK_CONVERT: number;
declare var VK_NONCONVERT: number;
declare var VK_ACCEPT: number;
declare var VK_MODECHANGE: number;
declare var VK_SPACE: number;
declare var VK_PRIOR: number;
declare var VK_NEXT: number;
declare var VK_END: number;
declare var VK_HOME: number;
declare var VK_LEFT: number;
declare var VK_UP: number;
declare var VK_RIGHT: number;
declare var VK_DOWN: number;
declare var VK_SELECT: number;
declare var VK_PRINT: number;
declare var VK_EXECUTE: number;
declare var VK_SNAPSHOT: number;
declare var VK_INSERT: number;
declare var VK_DELETE: number;
declare var VK_HELP: number;
declare var VK_LWIN: number;
declare var VK_RWIN: number;
declare var VK_APPS: number;
declare var VK_SLEEP: number;
declare var VK_NUMPAD0: number;
declare var VK_NUMPAD1: number;
declare var VK_NUMPAD2: number;
declare var VK_NUMPAD3: number;
declare var VK_NUMPAD4: number;
declare var VK_NUMPAD5: number;
declare var VK_NUMPAD6: number;
declare var VK_NUMPAD7: number;
declare var VK_NUMPAD8: number;
declare var VK_NUMPAD9: number;
declare var VK_MULTIPLY: number;
declare var VK_ADD: number;
declare var VK_SEPARATOR: number;
declare var VK_SUBTRACT: number;
declare var VK_DECIMAL: number;
declare var VK_DIVIDE: number;
declare var VK_F1: number;
declare var VK_F2: number;
declare var VK_F3: number;
declare var VK_F4: number;
declare var VK_F5: number;
declare var VK_F6: number;
declare var VK_F7: number;
declare var VK_F8: number;
declare var VK_F9: number;
declare var VK_F10: number;
declare var VK_F11: number;
declare var VK_F12: number;
declare var VK_F13: number;
declare var VK_F14: number;
declare var VK_F15: number;
declare var VK_F16: number;
declare var VK_F17: number;
declare var VK_F18: number;
declare var VK_F19: number;
declare var VK_F20: number;
declare var VK_F21: number;
declare var VK_F22: number;
declare var VK_F23: number;
declare var VK_F24: number;
declare var VK_NUMLOCK: number;
declare var VK_SCROLL: number;
declare var VK_OEM_NEC_EQUAL: number;
declare var VK_OEM_FJ_JISHO: number;
declare var VK_OEM_FJ_MASSHOU: number;
declare var VK_OEM_FJ_TOUROKU: number;
declare var VK_OEM_FJ_LOYA: number;
declare var VK_OEM_FJ_ROYA: number;
declare var VK_LSHIFT: number;
declare var VK_RSHIFT: number;
declare var VK_LCONTROL: number;
declare var VK_RCONTROL: number;
declare var VK_LMENU: number;
declare var VK_RMENU: number;
declare var VK_BROWSER_BACK: number;
declare var VK_BROWSER_FORWARD: number;
declare var VK_BROWSER_REFRESH: number;
declare var VK_BROWSER_STOP: number;
declare var VK_BROWSER_SEARCH: number;
declare var VK_BROWSER_FAVORITES: number;
declare var VK_BROWSER_HOME: number;
declare var VK_VOLUME_MUTE: number;
declare var VK_VOLUME_DOWN: number;
declare var VK_VOLUME_UP: number;
declare var VK_MEDIA_NEXT_TRACK: number;
declare var VK_MEDIA_PREV_TRACK: number;
declare var VK_MEDIA_STOP: number;
declare var VK_MEDIA_PLAY_PAUSE: number;
declare var VK_LAUNCH_MAIL: number;
declare var VK_LAUNCH_MEDIA_SELECT: number;
declare var VK_LAUNCH_APP1: number;
declare var VK_LAUNCH_APP2: number;
declare var VK_OEM_1: number;
declare var VK_OEM_PLUS: number;
declare var VK_OEM_COMMA: number;
declare var VK_OEM_MINUS: number;
declare var VK_OEM_PERIOD: number;
declare var VK_OEM_2: number;
declare var VK_OEM_3: number;
declare var VK_OEM_4: number;
declare var VK_OEM_5: number;
declare var VK_OEM_6: number;
declare var VK_OEM_7: number;
declare var VK_OEM_8: number;
declare var VK_PROCESSKEY: number;
declare var VK_ICO_CLEAR: number;
declare var VK_PACKET: number;
declare var VK_OEM_RESET: number;
declare var VK_OEM_JUMP: number;
declare var VK_OEM_PA1: number;
declare var VK_OEM_PA2: number;
declare var VK_OEM_PA3: number;
declare var VK_OEM_WSCTRL: number;
declare var VK_OEM_CUSEL: number;
declare var VK_OEM_ATTN: number;
declare var VK_OEM_FINISH: number;
declare var VK_OEM_COPY: number;
declare var VK_OEM_AUTO: number;
declare var VK_OEM_ENLW: number;
declare var VK_OEM_BACKTAB: number;
declare var VK_ATTN: number;
declare var VK_CRSEL: number;
declare var VK_EXSEL: number;
declare var VK_EREOF: number;
declare var VK_PLAY: number;
declare var VK_ZOOM: number;
declare var VK_NONAME: number;
declare var VK_PA1: number;
declare var VK_OEM_CLEAR: number;
declare var DelOnClose: number;
declare var HideOnClose: number;
declare var NoClose: number;
declare var atActivate: number;
declare var atDeactivate: number;
declare var atKillFocus: number;
declare var atSetFocus: number;
declare var wtDock: number;
declare var wtFloat: number;
declare var wtMDI: number;
declare var wtModal: number;
declare var wsNoStyle: number;
declare var wsSysMenu: number;
declare var wsMinimizeBox: number;
declare var wsMaximizeBox: number;
declare var wsHelpBox: number;
declare var wsBorder: number;
declare var wsCaption: number;
declare var wsSizable: number;
declare var wsCloseOnEscape: number;
declare var msNone: number;
declare var msPseudo: number;
declare var msModal: number;
declare var eTLFT_Unknown: number;
declare var eTLFT_Main: number;
declare var eTLFT_Hidden: number;
declare var vsDock: number;
declare var fsFloat: number;
declare var vsMDI: number;
declare var vsHardDock: number;
declare var vsHiding: number;
declare var vpNo: number;
declare var vpLeft: number;
declare var vpTop: number;
declare var vpRight: number;
declare var vpBottom: number;
declare var vpCenter: number;
declare var vpTabbed: number;
declare var ViewContextOffset: number;
declare var FocusedViewInCoreFrame: number;
declare var ActiveViewInCoreFrame: number;
declare var ViewContextInView: number;
declare var sizeof_ptr: number;
declare var mbp_size: number;
declare var mbp_i1_offset: number;
declare var mbp_i2_offset: number;
declare var mbp_p1_offset: number;
declare var SelectFileName_size: number;
declare var SelectFileName_mode_offset: number;
declare var SelectFileName_flags_offset: number;
declare var SelectFileName_filter_offset: number;
declare var SelectFileName_filterString_offset: number;
declare var SelectFileName_filterIndex_offset: number;
declare var SelectFileName_defExt_offset: number;
declare var SelectFileName_initialFileName_offset: number;
declare var SelectFileName_selectedFiles_offset: number;
declare var SelectFileName_directory_offset: number;
declare var SelectFileName_title_offset: number;
declare var TYPEATTR_size: number;
declare var TYPEATTR_guid_offset: number;
declare var TYPEATTR_lcid_offset: number;
declare var TYPEATTR_dwReserved_offset: number;
declare var TYPEATTR_memidConstructor_offset: number;
declare var TYPEATTR_memidDestructor_offset: number;
declare var TYPEATTR_lpstrSchema_offset: number;
declare var TYPEATTR_cbSizeInstance_offset: number;
declare var TYPEATTR_typekind_offset: number;
declare var TYPEATTR_cFuncs_offset: number;
declare var TYPEATTR_cVars_offset: number;
declare var TYPEATTR_cImplTypes_offset: number;
declare var TYPEATTR_cbSizeVft_offset: number;
declare var TYPEATTR_cbAlignment_offset: number;
declare var TYPEATTR_wTypeFlags_offset: number;
declare var TYPEATTR_wMajorVerNum_offset: number;
declare var TYPEATTR_wMinorVerNum_offset: number;
declare var TYPEATTR_tdescAlias_offset: number;
declare var TYPEATTR_idldescType_offset: number;
declare var FUNCDESC_size: number;
declare var FUNCDESC_memid_offset: number;
declare var FUNCDESC_lprgscode_offset: number;
declare var FUNCDESC_lprgelemdescParam_offset: number;
declare var FUNCDESC_funckind_offset: number;
declare var FUNCDESC_invkind_offset: number;
declare var FUNCDESC_callconv_offset: number;
declare var FUNCDESC_cParams_offset: number;
declare var FUNCDESC_cParamsOpt_offset: number;
declare var FUNCDESC_oVft_offset: number;
declare var FUNCDESC_cScodes_offset: number;
declare var CommandID_size: number;
declare var CommandID_group_offset: number;
declare var CommandID_num_offset: number;
declare var Command_size: number;
declare var Command_id_offset: number;
declare var Command_param_offset: number;
declare var Command_object_offset: number;
declare var ICmdSateImpl_size: number;
declare var ICmdSateImpl_id_offset: number;
declare var ICmdSateImpl_cmdState_offset: number;
declare var ICmdSateImpl_lstState_offset: number;
declare var KeyAccel_size: number;
declare var KeyAccel_text_offset: number;
declare var KeyAccel_vkCode_offset: number;
declare var KeyAccel_flags_offset: number;
declare var CompositeID_size: number;
declare var CompositeID_id_offset: number;
declare var CompositeID_uuid_offset: number;
declare var CompositeID_emptyUuid_offset: number;
declare var LineInfo_size: number;
declare var LineInfo_hasChild_offset: number;
declare var LineInfo_level_offset: number;
declare var LineInfo_expandable_offset: number;
declare var LineInfo_bookmark_offset: number;
declare var ImageInfo_size: number;
declare var ImageInfo_image_offset: number;
declare var ImageInfo_posInPicture_offset: number;
declare var ImageInfo_paintStyle_offset: number;
declare var CellFormat_size: number;
declare var CellFormat_text_offset: number;
declare var CellFormat_state_offset: number;
declare var CellFormat_image_offset: number;
declare var CellFormat_extImage_offset: number;
declare var CellFormat_clrBkg_offset: number;
declare var CellFormat_clrText_offset: number;
declare var CellFormat_font_offset: number;
declare var CellFormat_readOnly_offset: number;
declare var CellFormat_horAlign_offset: number;
declare var CellFormat_verAlign_offset: number;
declare var CellFormat_tooltip_offset: number;
declare var CellFormat_showAddCheck_offset: number;
declare var CellFormat_visible_offset: number;
declare var CellFormat_height_offset: number;
declare var CellFormat_autoHeight_offset: number;
declare var CellFormat_hyperLink_offset: number;
declare var CellFormat_v8Style_offset: number;
declare var CellFormat_validFields_offset: number;
declare var DocSink_size: number;
declare var DocSink_vtab_offset: number;
declare var DocSink_refCount_offset: number;
declare var DocSink_editHelper_offset: number;
declare var DocSink_propId_offset: number;
declare var StorageFileInfo_size: number;
declare var StorageFileInfo_name_offset: number;
declare var FileException_size: number;
declare var FileException_id_offset: number;
declare var FileException_descr_offset: number;
declare var FileException_ptr_offset: number;
declare var FileException_code_offset: number;
declare var FileException_url_offset: number;
declare var Font_size: number;
declare var Font_kind_offset: number;
declare var Font_lf_offset: number;
declare var Font_autoCharSet_offset: number;
declare var Font_style_offset: number;
declare var Font_validMask_offset: number;
declare var MDProperty_size: number;
declare var MDProperty_refs_offset: number;
declare var MDProperty_id_offset: number;
declare var MDProperty_nameEng_offset: number;
declare var MDProperty_nameRus_offset: number;
declare var MDProperty_i1_offset: number;
declare var MDProperty_i2_offset: number;
declare var MDProperty_resMod1_offset: number;
declare var MDProperty_resID_offset: number;
declare var MDProperty_resMod2_offset: number;
declare var MDProperty_resCatID_offset: number;
declare var MDProperty_pIType_offset: number;
declare var FieldInfo_size: number;
declare var FieldInfo_name1_offset: number;
declare var FieldInfo_name2_offset: number;
declare var FieldInfo_description_offset: number;
declare var FieldInfo_typeDomain_offset: number;
declare var FieldInfo_readOnly_offset: number;
declare var MDEventInfo_size: number;
declare var MDEventInfo_request_offset: number;
declare var MDEventInfo_result_offset: number;
declare var MDEventInfo_kind_offset: number;
declare var MDEventInfo_object_offset: number;
declare var MDEventInfo_parent_offset: number;
declare var MDEventInfo_id_offset: number;
declare var MDEventInfo_changedPropId_offset: number;
declare var TypeInfo_size: number;
declare var TypeInfo_typeId_offset: number;
declare var TypeInfo_name_offset: number;
declare var TypeInfo_priority_offset: number;
declare var TypeInfo_order_offset: number;
declare var TypeInfo_image_offset: number;
declare var TypeInfo_i1_offset: number;
declare var TypeInfo_compaundType_offset: number;
declare var TypeInfo_unMergeable_offset: number;
declare var TypeInfo_str_offset: number;
declare var MDTreeItemInfo_size: number;
declare var MDTreeItemInfo_id_offset: number;
declare var MDTreeItemInfo_text_offset: number;
declare var MDTreeItemInfo_editHelper_offset: number;
declare var MDTreeItemInfo_image_offset: number;
declare var V8Picture_size: number;
declare var V8Picture_kind_offset: number;
declare var V8Picture_cid_offset: number;
declare var V8Picture_url_offset: number;
declare var V8Picture_picture_offset: number;
declare var V8Picture_pxForTransparent_offset: number;
declare var V8Picture_withTransparent_offset: number;
declare var V8Picture_isGlyph_offset: number;
declare var V8Picture_ptGlyph_offset: number;
declare var V8Picture_szGlyph_offset: number;
declare var Glyph_size: number;
declare var Glyph_block_offset: number;
declare var Glyph_size_offset: number;
declare var Glyph_point_offset: number;
declare var Exception_size: number;
declare var Exception_id_offset: number;
declare var Exception_descr_offset: number;
declare var Exception_ptr_offset: number;
declare var Point_size: number;
declare var Point_x_offset: number;
declare var Point_y_offset: number;
declare var Size_size: number;
declare var Size_cx_offset: number;
declare var Size_cy_offset: number;
declare var Rect_size: number;
declare var Rect_left_offset: number;
declare var Rect_top_offset: number;
declare var Rect_right_offset: number;
declare var Rect_bottom_offset: number;
declare var Sci_CharacterRange_size: number;
declare var Sci_CharacterRange_cpMin_offset: number;
declare var Sci_CharacterRange_cpMax_offset: number;
declare var Sci_TextRange_size: number;
declare var Sci_TextRange_chrg_offset: number;
declare var Sci_TextRange_lpstrText_offset: number;
declare var Sci_TextToFind_size: number;
declare var Sci_TextToFind_chrg_offset: number;
declare var Sci_TextToFind_lpstrText_offset: number;
declare var Sci_TextToFind_chrgText_offset: number;
declare var Sci_Rectangle_size: number;
declare var Sci_Rectangle_left_offset: number;
declare var Sci_Rectangle_top_offset: number;
declare var Sci_Rectangle_right_offset: number;
declare var Sci_Rectangle_bottom_offset: number;
declare var Sci_NotifyHeader_size: number;
declare var Sci_NotifyHeader_hwndFrom_offset: number;
declare var Sci_NotifyHeader_idFrom_offset: number;
declare var Sci_NotifyHeader_code_offset: number;
declare var SCNotification_size: number;
declare var SCNotification_nmhdr_offset: number;
declare var SCNotification_position_offset: number;
declare var SCNotification_ch_offset: number;
declare var SCNotification_modifiers_offset: number;
declare var SCNotification_modificationType_offset: number;
declare var SCNotification_text_offset: number;
declare var SCNotification_length_offset: number;
declare var SCNotification_linesAdded_offset: number;
declare var SCNotification_message_offset: number;
declare var SCNotification_wParam_offset: number;
declare var SCNotification_lParam_offset: number;
declare var SCNotification_line_offset: number;
declare var SCNotification_foldLevelNow_offset: number;
declare var SCNotification_foldLevelPrev_offset: number;
declare var SCNotification_margin_offset: number;
declare var SCNotification_listType_offset: number;
declare var SCNotification_x_offset: number;
declare var SCNotification_y_offset: number;
declare var SCNotification_token_offset: number;
declare var SCNotification_annotationLinesAdded_offset: number;
declare var SCNotification_updated_offset: number;
declare var SCNotification_listCompletionMethod_offset: number;
declare var SqliteTransactionGuard_size: number;
declare var SqliteTransactionGuard_db_offset: number;
declare var SqliteTransactionGuard_success_offset: number;
declare var Vector_size: number;
declare var Vector_start_offset: number;
declare var Vector_end_offset: number;
declare var Vector_allocked_offset: number;
declare var v8strData_size: number;
declare var v8strData_refCount_offset: number;
declare var v8strData_text_offset: number;
declare var v8string_size: number;
declare var v8string_len_offset: number;
declare var v8string_data_offset: number;
declare var v8string_pEnd_offset: number;
declare var v8string_i1_offset: number;
declare var v8string_i2_offset: number;
declare var Color_size: number;
declare var Color_kind_offset: number;
declare var Color_value_offset: number;
declare var SyntaxItemInfo_size: number;
declare var SyntaxItemInfo_start_offset: number;
declare var SyntaxItemInfo_len_offset: number;
declare var SyntaxItemInfo_color_offset: number;
declare var SyntaxItemInfo_isBlock_offset: number;
declare var SyntaxItemInfo_blockKind_offset: number;
declare var SyntaxItemInfo_blockMode_offset: number;
declare var SyntaxItemInfo_lexemCategory_offset: number;
declare var SyntaxItemInfo_lexemType_offset: number;
declare var SyntaxItemInfos_size: number;
declare var SyntaxItemInfos_refCount_offset: number;
declare var SyntaxItemInfos_infos_offset: number;
declare var BackColorsItem_size: number;
declare var BackColorsItem_start_offset: number;
declare var BackColorsItem_len_offset: number;
declare var BackColorsItem_color_offset: number;
declare var TextPosition_size: number;
declare var TextPosition_vtable_offset: number;
declare var TextPosition_line_offset: number;
declare var TextPosition_col_offset: number;
declare var LocalWString_size: number;
declare var TypeDomainPattern_size: number;
declare var TypeDomainPattern_ptr_offset: number;
declare var TypeContextInfoItem_size: number;
declare var TypeContextInfoItem_name_offset: number;
declare var TypeContextInfoItem_isMethod_offset: number;
declare var TypeContextInfoItem_haveRetVal_offset: number;
declare var TypeContextInfoItem_params_offset: number;
declare var TypeContextInfoItem_from_offset: number;
declare var TypeContextInfoItem_typeDomain_offset: number;
declare var TypeContextInfoItem_lst_0_offset: number;
declare var TypeContextInfoItem_lst_4_offset: number;
declare var TypeContextInfoItem_flag1_offset: number;
declare var TypeContextInfoItem_flag0_1_offset: number;
declare var TypeContextInfoItem_flag0_2_offset: number;
declare var TypeContextInfoItem_objectId_offset: number;
declare var TypeContextInfoItem_mdPropId_offset: number;
declare var TypeContextInfoItem_isTypeSource_offset: number;
declare var TypeContextInfoItem_providedTypeDomain_offset: number;
declare var TypeContextInfoItem_str1_offset: number;
declare var TypeContextInfoItem_str2_offset: number;
declare var TypeContextInfoItem_byte_0_offset: number;
declare var TypeContextInfoItem_someVector_offset: number;
declare var TypeNameInfo_size: number;
declare var TypeNameInfo_name_offset: number;
declare var TypeNameInfo_uuid_offset: number;
declare var ContextValueInfo_size: number;
declare var ContextValueInfo_nameEng_offset: number;
declare var ContextValueInfo_nameRus_offset: number;
declare var ContextValueInfo_typeDomainPattern_offset: number;
declare var ContextValueInfo_isMutable_offset: number;
declare var ContextValueInfo_zero1_offset: number;
declare var ContextValueInfo_zero2_offset: number;
declare var ContextValueInfo_pZero1_offset: number;
declare var ContextValueInfo_pZero2_offset: number;
declare var ContextValueInfo_zero3_offset: number;
declare var URL_size: number;
declare var URL_url_offset: number;
declare var URL_vec_offset: number;
declare var URL_b1_offset: number;
declare var URL_b2_offset: number;
declare var Date_size: number;
declare var Date_ticks_offset: number;
declare var Numeric_size: number;
declare var Numeric_allocked_offset: number;
declare var Numeric_length_offset: number;
declare var Numeric_prec_offset: number;
declare var Numeric__sign_offset: number;
declare var Numeric_data_offset: number;
declare var Numeric_inplace1_offset: number;
declare var Numeric_inplace2_offset: number;
declare var Numeric_inplace3_offset: number;
declare var Numeric_inplace4_offset: number;
declare var Value_size: number;
declare var Value_vtable_offset: number;
declare var Value_pValue_offset: number;
declare var Type_size: number;
declare var Type_pType_offset: number;
declare var VTColumnInfo_size: number;
declare var VTColumnInfo_name1_offset: number;
declare var VTColumnInfo_name2_offset: number;
declare var VTColumnInfo_type_offset: number;
declare var VTColumnInfo_title_offset: number;
declare var VTColumnInfo_width_offset: number;
declare var StructKeys_size: number;
declare var StructKeys_key1_offset: number;
declare var StructKeys_key2_offset: number;
declare var LOGFONT_size: number;
declare var LOGFONT_lfHeight_offset: number;
declare var LOGFONT_lfWidth_offset: number;
declare var LOGFONT_lfEscapement_offset: number;
declare var LOGFONT_lfOrientation_offset: number;
declare var LOGFONT_lfWeight_offset: number;
declare var LOGFONT_lfItalic_offset: number;
declare var LOGFONT_lfUnderline_offset: number;
declare var LOGFONT_lfStrikeOut_offset: number;
declare var LOGFONT_lfCharSet_offset: number;
declare var LOGFONT_lfOutPrecision_offset: number;
declare var LOGFONT_lfClipPrecision_offset: number;
declare var LOGFONT_lfQuality_offset: number;
declare var LOGFONT_lfPitchAndFamily_offset: number;
declare var LOGFONT_lfFaceNameStart_offset: number;
declare var LOGFONT_lfFaceNameEnd_offset: number;
declare var MONITORINFO_size: number;
declare var MONITORINFO_cbSize_offset: number;
declare var MONITORINFO_rcMonitor_offset: number;
declare var MONITORINFO_rcWork_offset: number;
declare var MONITORINFO_dwFlags_offset: number;
declare var MSG_size: number;
declare var MSG_hwnd_offset: number;
declare var MSG_message_offset: number;
declare var MSG_wParam_offset: number;
declare var MSG_lParam_offset: number;
declare var MSG_time_offset: number;
declare var MSG_ptx_offset: number;
declare var MSG_pty_offset: number;
declare var MINMAXINFO_size: number;
declare var MINMAXINFO_ptReserved_offset: number;
declare var MINMAXINFO_ptMaxSize_offset: number;
declare var MINMAXINFO_ptMaxPosition_offset: number;
declare var MINMAXINFO_ptMinTrackSize_offset: number;
declare var MINMAXINFO_ptMaxTrackSize_offset: number;
declare var IMDIClient_size: number;
declare var IMDIClient_childsIds_offset: number;
declare var ViewContextListNode_size: number;
declare var ViewContextListNode_next_offset: number;
declare var ViewContextListNode_prev_offset: number;
declare var ViewContextListNode_view_offset: number;
declare var ViewContextList_size: number;
declare var ViewContextList_head_offset: number;
declare var ViewContextList_end_offset: number;
declare var ViewPosition_size: number;
declare var ViewPosition_state_offset: number;
declare var ViewPosition_unk1_offset: number;
declare var ViewPosition_unk2_offset: number;
declare var ViewPosition_area_offset: number;
declare var ViewPosition_dockLine_offset: number;
declare var ViewPosition_dockOffset_offset: number;
declare var ViewPosition_dockSize_offset: number;
declare var ViewPosition_canSplit_offset: number;
declare var ViewPosition_floatRect_offset: number;
declare var ViewPosition_MDI_Rect_offset: number;
declare var ViewPosition_MDI_maxed_offset: number;
declare var ViewPosition_autoHideSize_offset: number;
declare var ViewPosition_stateAbility_offset: number;
declare var ViewPosition_areaAbility_offset: number;
declare var ViewPosition_splitAbility_offset: number;
declare var ViewPosition_MDI_ViewData_offset: number;
declare var ViewPosition_floatViewData_offset: number;
declare var ViewPosition_dockViewData_offset: number;
declare var ViewPosition_autoHideViewData_offset: number;
declare var ViewPosition_center_offset: number;
declare var ViewPosition_unk3_offset: number;
declare var ViewPosition_unk4_offset: number;
declare var ViewPosition_unk5_offset: number;
declare var ViewPosition_unk6_offset: number;
declare var ViewContext_size: number;
declare var ViewContext_id_offset: number;
declare var ViewContext_vpCurrent_offset: number;
declare var ViewContext_vpOriginal_offset: number;
declare var ViewContext_sizeOriginal_offset: number;
declare var ViewContext_parent_offset: number;
declare var tagRECT_size: number;
declare var tagRECT_left_offset: number;
declare var tagRECT_top_offset: number;
declare var tagRECT_right_offset: number;
declare var tagRECT_bottom_offset: number;
declare var Guid_size: number;
declare var sfrNormal: number;
declare var sfrSelected: number;
declare var sfrCanceled: number;
declare var dsAnsi: number;
declare var dsUtf8: number;
declare var dsUtf16: number;
declare var mdeAdd: number;
declare var mdeChangeProp: number;
declare var mdeDelete: number;
declare var mdeChange: number;
declare var mdeSave: number;
declare var mdeClose: number;
declare var mdeAfterSave: number;
declare var mdeOpen: number;
declare var pflSeanse: number;
declare var pflComputer: number;
declare var pflBase: number;
declare var pflBaseUser: number;
declare var pflCompBase: number;
declare var pflCompBaseUser: number;
declare var pflSnegopat: number;
declare var addRowError: number;
declare var addRowSuccess: number;
declare var addRowBreak: number;
declare var E_NOTIMPL: number;
declare var E_FAIL: number;
declare var maxMethCount: number;
declare var vctNo: number;
declare var vctTabbed: number;
declare var vctTwoViewsHorz: number;
declare var vctTwoViewsVert: number;
declare var vctMdiContainer: number;
declare var vctUnknown: number;
declare var beforeDoModal: number;
declare var openModalWnd: number;
declare var afterDoModal: number;
declare var afterInitial: number;
declare var dstGrid: number;
declare var dstTree: number;
declare var useLangEng: number;
declare var useLangRus: number;
declare var ltUnknown: number;
declare var ltRemark: number;
declare var ltQuote: number;
declare var ltDate: number;
declare var ltNumber: number;
declare var ltPreproc: number;
declare var ltDirective: number;
declare var ltLabel: number;
declare var ltLPar: number;
declare var ltRPar: number;
declare var ltLBrt: number;
declare var ltRBrt: number;
declare var ltEqual: number;
declare var ltComma: number;
declare var ltSemicolon: number;
declare var ltPlus: number;
declare var ltMinus: number;
declare var ltMult: number;
declare var ltDivide: number;
declare var ltMod: number;
declare var ltQuestion: number;
declare var ltPeriod: number;
declare var ltLess: number;
declare var ltLessEq: number;
declare var ltGrat: number;
declare var ltGratEq: number;
declare var ltNotEq: number;
declare var ltName: number;
declare var ltIf: number;
declare var ltThen: number;
declare var ltElsIf: number;
declare var ltEndIf: number;
declare var ltElse: number;
declare var ltFor: number;
declare var ltEach: number;
declare var ltIn: number;
declare var ltTo: number;
declare var ltWhile: number;
declare var ltDo: number;
declare var ltEndDo: number;
declare var ltProcedure: number;
declare var ltFunction: number;
declare var ltEndProcedure: number;
declare var ltEndFunction: number;
declare var ltVar: number;
declare var ltGoto: number;
declare var ltReturn: number;
declare var ltContinue: number;
declare var ltBreak: number;
declare var ltAnd: number;
declare var ltOr: number;
declare var ltNot: number;
declare var ltTry: number;
declare var ltExcept: number;
declare var ltRaise: number;
declare var ltEndTry: number;
declare var ltNew: number;
declare var ltExecute: number;
declare var ltTrue: number;
declare var ltFalse: number;
declare var ltAddHandler: number;
declare var ltRemoveHandler: number;
declare var ltExport: number;
declare var ltNull: number;
declare var ltUndefined: number;
declare var ltVal: number;
declare var pctServer: number;
declare var pctExtConnect: number;
declare var pctThickClientOrdinaryApplication: number;
declare var pctThickClientManagedApplication: number;
declare var pctThinClient: number;
declare var pctWebClient: number;
declare var pctFS_Server_ThickOrdinary: number;
declare var pctFS_Server_ThickManaged: number;
declare var pctFS_Server_ExtCnn: number;
declare var pctMobServer: number;
declare var pctMobClient: number;
declare var pctCount: number;
declare var pctLast: number;
declare var amSrv: number;
declare var amThk: number;
declare var amThn: number;
declare var amWeb: number;
declare var amExt: number;
declare var amMSr: number;
declare var amMCl: number;
declare var amCount: number;
declare var allowProcedure: number;
declare var allowFunction: number;
declare var allowModuleVar: number;
declare var allowGCProp: number;
declare var allowNewTypes: number;
declare var allowObjMethods: number;
declare var allowObjProps: number;
declare var nothingToDone: number;
declare var inExpression: number;
declare var inFunction: number;
declare var inProcedure: number;
declare var inSelectHandler: number;
declare var wantCollection: number;
declare var wantHandlers: number;
declare var wantProcName: number;
declare var wantFuncName: number;
declare var wantMVarName: number;
declare var wantLVarName: number;
declare var wantParamName: number;
declare var wantTypeName: number;
declare var wantDefVal: number;
declare var inIndex: number;
declare var afterCompare: number;
declare var needFastReparse: number;
declare var allowDirective: number;
declare var hasParam: number;
declare var hasParamNew: number;
declare var noSemicolon: number;
declare var lvParam: number;
declare var lvVar: number;
declare var lvAuto: number;
declare var ecNone: number;
declare var ecAtServer: number;
declare var ecAtClient: number;
declare var ecAtClientAtServer: number;
declare var ecAtServerNoContext: number;
declare var ecAtClientAtServerNoContext: number;
declare var cmdStateHandler: number;
declare var cmdStateEnabled: number;
declare var cmdStateChecked: number;
declare var editFontDelta: number;
declare var ctrlDelta: number;
declare var editID: number;
declare var boxID: number;
declare var elProcEx: number;
declare var elFuncEx: number;
declare var elVarEx: number;
declare var elProc: number;
declare var elFunc: number;
declare var elVar: number;
declare var elLast: number;
declare var parenthesis: number;
declare var parenthesisWithBackSpace: number;
declare var squareBracket: number;
declare var quote: number;
declare var date: number;
declare var question: number;
declare var lastType: number;
declare var modeNone: number;
declare var modeQuote: number;
declare var modeName: number;
declare var modePreproc: number;
declare var piOnMainEnter: number;
declare var piOnMainWindow: number;
declare var piOnFirstIdle: number;
declare var piOnDesignerInit: number;
declare var imgNone: number;
declare var imgPublicMethod: number;
declare var imgPublicVar: number;
declare var imgKeyword: number;
declare var imgType: number;
declare var imgParenthesis: number;
declare var imgMethodWithKey: number;
declare var imgVarWithKey: number;
declare var imgLocalVar: number;
declare var imgEvent: number;
declare var imgCmnModule: number;
declare var imgEnums: number;
declare var imgCtxMethod: number;
declare var imgCtxVar: number;
declare var stockBuiltin: number;
declare var stockTypeNames: number;
declare var stockGlobalProc: number;
declare var stockGlobalFunc: number;
declare var stockGlobalFuncInExpr: number;
declare var stockGlobalProps: number;
declare var stockSysEnums: number;
declare var stockLast: number;
declare var langEng: number;
declare var langRus: number;
declare var langCmn: number;
declare var langLast: number;
declare var scgProcedure: number;
declare var scgFunction: number;
declare var scgProperty: number;
declare var scgLast: number;
declare var KEYEVENTF_EXTENDEDKEY: number;
declare var KEYEVENTF_KEYUP: number;
declare var KEYEVENTF_SCANCODE: number;
declare var MAPVK_VK_TO_VSC: number;
declare var MAPVK_VSC_TO_VK: number;
declare var MAPVK_VK_TO_CHAR: number;
declare var MAPVK_VSC_TO_VK_EX: number;
declare var SW_HIDE: number;
declare var SW_SHOWNORMAL: number;
declare var SW_NORMAL: number;
declare var SW_SHOWMINIMIZED: number;
declare var SW_SHOWMAXIMIZED: number;
declare var SW_MAXIMIZE: number;
declare var SW_SHOWNOACTIVATE: number;
declare var SW_SHOW: number;
declare var SW_MINIMIZE: number;
declare var SW_SHOWMINNOACTIVE: number;
declare var SW_SHOWNA: number;
declare var SW_RESTORE: number;
declare var SW_SHOWDEFAULT: number;
declare var SW_FORCEMINIMIZE: number;
declare var SW_MAX: number;
declare var WS_OVERLAPPED: number;
declare var WS_POPUP: number;
declare var WS_CHILD: number;
declare var WS_MINIMIZE: number;
declare var WS_VISIBLE: number;
declare var WS_DISABLED: number;
declare var WS_CLIPSIBLINGS: number;
declare var WS_CLIPCHILDREN: number;
declare var WS_MAXIMIZE: number;
declare var WS_CAPTION: number;
declare var WS_BORDER: number;
declare var WS_DLGFRAME: number;
declare var WS_VSCROLL: number;
declare var WS_HSCROLL: number;
declare var WS_SYSMENU: number;
declare var WS_THICKFRAME: number;
declare var WS_GROUP: number;
declare var WS_TABSTOP: number;
declare var ES_NOHIDESEL: number;
declare var ES_AUTOHSCROLL: number;
declare var WS_EX_CLIENTEDGE: number;
declare var SWP_NOSIZE: number;
declare var SWP_NOMOVE: number;
declare var SWP_NOZORDER: number;
declare var SWP_NOREDRAW: number;
declare var SWP_NOACTIVATE: number;
declare var SWP_FRAMECHANGED: number;
declare var SWP_SHOWWINDOW: number;
declare var SWP_HIDEWINDOW: number;
declare var SWP_NOCOPYBITS: number;
declare var SWP_NOOWNERZORDER: number;
declare var SWP_NOSENDCHANGING: number;
declare var HWND_TOP: number;
declare var HWND_BOTTOM: number;
declare var HWND_TOPMOST: number;
declare var HWND_NOTOPMOST: number;
declare var LOGPIXELSX: number;
declare var LOGPIXELSY: number;
declare var MONITOR_DEFAULTTONULL: number;
declare var MONITOR_DEFAULTTOPRIMARY: number;
declare var MONITOR_DEFAULTTONEAREST: number;
declare var SM_CXSCREEN: number;
declare var SM_CYSCREEN: number;
declare var PAGE_EXECUTE_READWRITE: number;
declare var DONT_RESOLVE_DLL_REFERENCES: number;
declare var LOAD_LIBRARY_AS_DATAFILE: number;
declare var LOAD_WITH_ALTERED_SEARCH_PATH: number;
declare var LOAD_IGNORE_CODE_AUTHZ_LEVEL: number;
declare var LOAD_LIBRARY_AS_IMAGE_RESOURCE: number;
declare var LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE: number;
declare var LOAD_LIBRARY_REQUIRE_SIGNED_TARGET: number;
declare var GWL_STYLE: number;
declare var GWL_EXSTYLE: number;
declare var WMSZ_LEFT: number;
declare var WMSZ_RIGHT: number;
declare var WMSZ_TOP: number;
declare var WMSZ_TOPLEFT: number;
declare var WMSZ_TOPRIGHT: number;
declare var WMSZ_BOTTOM: number;
declare var WMSZ_BOTTOMLEFT: number;
declare var WMSZ_BOTTOMRIGHT: number;
declare var CP_ACP: number;
declare var CP_OEMCP: number;
declare var CP_MACCP: number;
declare var CP_THREAD_ACP: number;
declare var CP_SYMBOL: number;
declare var CP_UTF7: number;
declare var CP_UTF8: number;
declare var addins: AddinMgr;
declare var profileRoot: ProfileStore;
declare var snegopat: Snegopat;
declare var hotkeys: IHotKeys;
declare var events: IEventConnector;
declare var windows: IV8Windows;
declare var metadata: IV8MetaData;
declare var v8files: V8Files;
declare var develop: Develop;
declare var env: EnvironmentData;
declare var cmdService: CommandService;
declare var winApi: WinApi;
declare function v8New(name: string, ... params);
declare function Message(text: string, markerOrPict?, clickHandler?: Object, handlerArg?): void;
declare function MessageBox(text: string, style?: number, caption?: string, timeout?: number): number;
declare function globalContext(uuidStr: string);
declare function designInternalForm(path?: string): void;
declare function designScriptForm(path?: string): void;
declare function loadScriptForm(path: string, eventHandler: Object, eventPrefix?: string);
declare function loadScriptFormEpf(path: string, formName: string, eventHandler: Object, eventPrefix?: string);
declare function toV8Value(varValue): V8Value;
declare function getCmdState(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): ICmdUpdateResult;
declare function sendCommand(cmdGroupUUID: string, cmdNumber: number, subCommandIdx?: number): boolean;
declare function createTimer(msec: number, pDisp: Object, member?: string): number;
declare function killTimer(timerID: number): void;
declare function saveProfile(): void;
declare function snPrint(msg: string): void;
declare function snLog(msg: string): void;
declare var editorsManager: EditorsManager;
declare function loadResourceString(moduleName: string, stringID: string): string;
declare function builtin_require(addinFile: string);
declare function sqliteOpen(baseName?: string, flags?: number): SqliteBase;
declare var Designer: _IfaceDesigner;
declare var SelfScript: _IfaceSelfScript;
